# yamllint disable rule:line-length
---
name: Deploy All
on:  # yamllint disable-line rule:truthy
  workflow_dispatch:

jobs:
  colmena-apply:
    runs-on: native
    steps:
      - name: Checkout git repo
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Add SSH key
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
            mkdir -p /home/runner/.ssh
            ssh-keyscan -f my_hosts >> /home/runner/.ssh/known_hosts
            echo "${{ secrets.SSH_DEPLOY_PRIVKEY }}" > /home/runner/.ssh/github_actions
            chmod 600 /home/runner/.ssh/github_actions
            ssh-agent -a $SSH_AUTH_SOCK > /dev/null
            ssh-add /home/runner/.ssh/github_actions
      - name: Go Go Go!
        run: /run/current-system/sw/bin/nix run github:zhaofengli/colmena -- apply switch
