# yamllint disable rule:line-length
---
name: Nixinate
on:  # yamllint disable-line rule:truthy
  workflow_dispatch:
    inputs:
      target_host:
        description: 'Target Host'
        required: true
        default: 'lxc-audiobookshelf'
        type: choice
        options:
          - lxc-audiobookshelf
          - lxc-mkdocs-tcsnlps

jobs:
  nixinate:
    runs-on: native
    env:
      TARGET_HOST: 'lxc-mkdocs-tcsnlps'
    steps:
      - name: Checkout git repo
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Nixinate!
        run: /run/current-system/sw/bin/nix run .#apps.nixinate.${{ inputs.target_host }}
