# yamllint disable rule:line-length
---
name: Nixinate
on:  # yamllint disable-line rule:truthy
  workflow_dispatch:
jobs:
  nixinate:
    runs-on: native
    env:
      TARGET_HOST: 'lxc-mkdocs-tcsnlps'
    steps:
      - name: Checkout git repo
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Nixinate!
        run: nix run .#apps.nixinate.#TARGET_HOST
