# yamllint disable rule:line-length
---
name: Deploy-Flake
on:  # yamllint disable-line rule:truthy
  workflow_dispatch:
jobs:
  deploy-mkdocs:
    runs-on: native
    steps:
      - name: Checkout git repo
        uses: actions/checkout@v4
        with:
          submodules: true