{ pkgs, ... }:
{
  imports = [
    ./fonts.nix
  ];
  environment.variables = {
    SSH_AUTH_SOCK = "$HOME/.bitwarden-ssh-agent.sock";
    NIXOS_OZONE_WL=1;
  };
  environment.systemPackages = with pkgs; [
    (hiPrio papirus-icon-theme)
    age
    alsa-plugins
    android-studio
    android-tools
    android-udev-rules
    btop
    direnv
    dmidecode
    easyeffects
    edid-decode
    epson-escpr
    epson-escpr2
    epsonscan2
    ethtool
    exfat
    exfatprogs
    fastfetch
    fzf
    gcc
    gearlever
    git
    google-chrome
    haskellPackages.rtlsdr
    htop
    hunspell
    hunspellDicts.en_US
    hunspellDicts.nl_NL
    intel-gpu-tools
    libreoffice
    libva-utils
    lm_sensors
    lsd
    lshw
    mono
    neovim
    nil
    nix-search-cli
    nixd
    nixos-generators
    parabolic
    pavucontrol
    pciutils
    python312Packages.pip
    python3Full
    qtscrcpy
    retroarch
    rtl-sdr-librtlsdr
    scrcpy
    sdrpp
    soapyrtlsdr
    solaar
    tailscale
    tdrop
    throttled
    usbutils
    yt-dlp
  ];
}
